add branch name condition

diff --git a/.github/workflows/dummy_rc_flow.yml b/.github/workflows/dummy_rc_flow.yml
--- a/.github/workflows/dummy_rc_flow.yml
+++ b/.github/workflows/dummy_rc_flow.yml
@@ -23,6 +23,13 @@ jobs:
         with:
           node-version: 20
 
+
+      - name: Check branch for release cut
+        if: ${{ github.ref_name != 'main' || !startsWith(github.ref_name, 'release') }}
+        run: |
+          echo "branch ${{ github.ref_name }} cannot be used for release cut
+          exit 1
+
       - name: Configure github
         run: |
           git config user.email "samuel.son@google.com"
